
const products = [
    { id: "strawberry", name: "Strawberry Rush", price: 149, image: "strawberry.jpg", desc: "Sweet strawberry juice with a bright, juicy finish.", tag: "Berry" },
    { id: "lemon", name: "Lemon Lime", price: 129, image: "lemon.jpg", desc: "Zesty citrus refreshment with a crisp, clean finish.", tag: "Citrus" },
    { id: "orange", name: "Orange Splash", price: 139, image: "orange.jpg", desc: "Fresh orange flavour made for sunny moments.", tag: "Citrus" },
    { id: "apple", name: "Apple Fresh", price: 149, image: "apple.jpg", desc: "Crisp apple goodness with a premium smooth taste.", tag: "Fruit" },
    { id: "mango", name: "Mango Blast", price: 159, image: "mango.jpg", desc: "Rich golden mango flavour with a tropical kick.", tag: "Tropical" },
];
const $ = s => document.querySelector(s), $$ = s => document.querySelectorAll(s);
function cart() { return JSON.parse(localStorage.getItem("jinmazaCart") || "[]") }
function saveCart(c) { localStorage.setItem("jinmazaCart", JSON.stringify(c)); updateCartCount() }
function updateCartCount() { let n = cart().reduce((a, x) => a + x.qty, 0); $$(".cart-count").forEach(e => e.textContent = n) }
function addToCart(id, qty = 1) { let c = cart(), p = products.find(x => x.id === id), i = c.findIndex(x => x.id === id); if (i > -1) c[i].qty += qty; else c.push({ ...p, qty }); saveCart(c); toast(p.name + " added to cart") }
function toast(msg) { let t = $("#toast"); if (!t) { t = document.createElement("div"); t.id = "toast"; t.style.cssText = "position:fixed;right:20px;bottom:20px;z-index:2000;background:#10231d;color:#fff;padding:15px 20px;border-radius:14px;font-weight:800;box-shadow:0 15px 40px #0003"; document.body.appendChild(t) } t.textContent = "✓ " + msg; t.style.opacity = 1; clearTimeout(window.__toast); window.__toast = setTimeout(() => t.style.opacity = 0, 1800) }
function card(p) { return `<article class="card reveal" data-name="${p.name.toLowerCase()}" data-tag="${p.tag.toLowerCase()}"><div class="card-media"><img src="${p.image}" alt="${p.name}"></div><div class="card-body"><div style="font-size:11px;font-weight:900;color:#087b52;text-transform:uppercase;letter-spacing:.12em">${p.tag}</div><h3>${p.name}</h3><p>${p.desc}</p><div style="display:flex;justify-content:space-between;align-items:center"><span class="price">₹${p.price}</span><span>★★★★★</span></div><div class="card-actions"><a class="btn btn-light" href="product.html?id=${p.id}">View</a><button class="btn btn-green" onclick="addToCart('${p.id}')">Add</button></div></div></article>` }
function renderProducts(target, filter = "", tag = "all") { let el = $(target); if (!el) return; let list = products.filter(p => (p.name.toLowerCase().includes(filter) || p.desc.toLowerCase().includes(filter)) && (tag === "all" || p.tag.toLowerCase() === tag)); el.innerHTML = list.map(card).join("") || `<div class="empty" style="grid-column:1/-1">No flavour found.</div>`; observe() }
function observe() { let o = new IntersectionObserver(es => es.forEach(e => { if (e.isIntersecting) e.target.classList.add("show") }), { threshold: .12 }); $$(".reveal:not(.show)").forEach(x => o.observe(x)) }
function initNav() { let menu = $(".menu"), links = $(".navlinks"); if (menu) menu.onclick = () => links.classList.toggle("open"); let page = location.pathname.split("/").pop() || "index.html"; $$(".navlinks a").forEach(a => { if (a.getAttribute("href") === page) a.classList.add("active") }); updateCartCount() }
function initSlider() { let slides = $$(".hero-slide"); if (!slides.length) return; let i = 0; function go(n) { slides.forEach((s, k) => s.classList.toggle("active", k === n)); $$(".slide-dot").forEach((d, k) => d.classList.toggle("active", k === n)); i = n } $$(".next").forEach(b => b.onclick = () => go((i + 1) % slides.length)); $$(".prev").forEach(b => b.onclick = () => go((i - 1 + slides.length) % slides.length)); $$(".slide-dot").forEach((d, k) => d.onclick = () => go(k)); setInterval(() => go((i + 1) % slides.length), 4500) }
function initTilt() { document.addEventListener("mousemove", e => { let b = $(".hero-product-img"); if (!b) return; let x = (e.clientX / innerWidth - .5) * 12, y = (e.clientY / innerHeight - .5) * -8; b.style.transform = `rotateY(${-10 + x}deg) rotateX(${3 + y}deg)` }) }
function initShop() { let grid = $("#productGrid"); if (!grid) return; renderProducts("#productGrid"); let search = $("#search"), select = $("#category"); function run() { renderProducts("#productGrid", search.value.toLowerCase(), select.value) } search.oninput = run; select.onchange = run }
function initProduct() { let box = $("#productDetail"); if (!box) return; let id = new URLSearchParams(location.search).get("id") || "mango", p = products.find(x => x.id === id) || products[0]; box.innerHTML = `<div class="detail-image"><img src="${p.image}" alt="${p.name}"></div><div><div class="eyebrow">${p.tag} collection</div><h1>${p.name}</h1><div class="price">₹${p.price}</div><p>${p.desc} Crafted for a bold, refreshing sip with a premium visual identity.</p><div class="size-row"><button class="size active">250 ml</button><button class="size">500 ml</button><button class="size">1 L</button></div><div style="display:flex;gap:12px;align-items:center;margin:20px 0"><div class="qty"><button id="minus">−</button><span id="qty">1</span><button id="plus">+</button></div><button class="btn btn-green" id="add">Add to cart</button></div><div style="margin-top:28px;padding-top:22px;border-top:1px solid var(--line)"><b>Ingredients</b><p style="margin-top:8px">Fruit juice, filtered water, natural flavour, vitamin blend.</p></div></div>`; let q = 1; $("#minus").onclick = () => { q = Math.max(1, q - 1); $("#qty").textContent = q }; $("#plus").onclick = () => { $("#qty").textContent = ++q }; $("#add").onclick = () => addToCart(p.id, q) }
function initCart() { let box = $("#cartItems"); if (!box) return; function render() { let c = cart(); if (!c.length) { box.innerHTML = '<div class="empty">Your cart is empty.<br><br><a class="btn btn-green" href="products.html">Explore flavours</a></div>'; $("#cartSummary").innerHTML = ""; return } box.innerHTML = '<div class="cart-row head"><b>PRODUCT</b><b>PRICE</b><b>QTY</b><b>TOTAL</b></div>' + c.map((p, i) => `<div class="cart-row"><div class="cart-product"><img src="${p.image}"><div><b>${p.name}</b><div style="color:#63746e;font-size:13px">${p.tag}</div></div></div><div>₹${p.price}</div><div class="qty"><button onclick="changeQty(${i},-1)">−</button><span>${p.qty}</span><button onclick="changeQty(${i},1)">+</button></div><div><b>₹${p.price * p.qty}</b> <button onclick="removeItem(${i})" style="border:0;background:none;cursor:pointer;margin-left:10px">✕</button></div></div>`).join(""); let sub = c.reduce((a, p) => a + p.price * p.qty, 0); $("#cartSummary").innerHTML = `<div class="summary-line"><span>Subtotal</span><b>₹${sub}</b></div><div class="summary-line"><span>Delivery</span><b>Free</b></div><div class="summary-line total"><span>Total</span><b>₹${sub}</b></div><a class="btn btn-orange" style="width:100%;margin-top:18px" href="checkout.html">Proceed to checkout</a>` } window.changeQty = (i, d) => { let c = cart(); c[i].qty += d; if (c[i].qty < 1) c.splice(i, 1); saveCart(c); render() }; window.removeItem = i => { let c = cart(); c.splice(i, 1); saveCart(c); render() }; render() }
document.addEventListener("DOMContentLoaded", () => { initNav(); initSlider(); initTilt(); initShop(); initProduct(); initCart(); observe(); $$(".add-product").forEach(b => b.onclick = () => addToCart(b.dataset.id)); });
